# Generated by Django 3.0.8 on 2020-07-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmegimage',
            old_name='quantised_picture',
            new_name='quantized_picture',
        ),
        migrations.AddField(
            model_name='kmegimage',
            name='quantized_thumb_nail',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='kmegimage',
            name='thumb_nail',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
