# Generated by Django 3.0.8 on 2020-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeg', '0002_auto_20200719_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmegimage',
            name='quantized_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='kmegimage',
            name='quantized_thumb_nail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='kmegimage',
            name='thumb_nail',
            field=models.ImageField(upload_to=''),
        ),
    ]
