# Generated by Django 3.0.8 on 2020-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmeg', '0003_auto_20200719_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmegimage',
            name='quantized_picture',
            field=models.ImageField(upload_to='', verbose_name='default.jpg'),
        ),
        migrations.AlterField(
            model_name='kmegimage',
            name='quantized_thumb_nail',
            field=models.ImageField(upload_to='', verbose_name='default.jpg'),
        ),
        migrations.AlterField(
            model_name='kmegimage',
            name='thumb_nail',
            field=models.ImageField(upload_to='', verbose_name='default.jpg'),
        ),
    ]
